### PR TITLE
add support for STM32MP157F-DK2 with working OPP

### PR DESCRIPTION
**Pull request by 0xDRRB**
add support for STM32MP157**F**-DK2 , and new DTS files that get rid of the "cpu cpu0: OPP table can't be empty" message at boot.
(STM32MP157A-DK1 and STM32MP157C-DK2 are reported as obsolete in STM32CubeMX now)

### CODE REVIEW

**Comment by samuelpowell** [comment]
@0xDRRB was there a specific change you made to fix the performance point issues (that can be backported to the A/C devices), or is it just that the generated/included dts have the appropriate entries?

**Comment by 0xDRRB** [comment]
@samuelpowell  The "stm32mp157f-dk2-mx.dts" file (generated by STM32CubeMX) in this PR includes "stm32mp15xf.dtsi" which itself includes "stm32mp15xd.dtsi" where the correct configuration of the OPP table is.

If you take a look at "stm32mp15xa.dtsi" (included from "stm32mp15xc.dtsi"), you will see that there is only one frequency in the OPP table: 650 Mhz. This is the maximum speed of A/C devices, and the main difference between STM32MP157 A/C and STM32MP157 D/F.

**Comment by samuelpowell** [comment]
Thanks @0xDRRB, I understand. I also found that I had to enable the 'PLL1 User defined configuration' option in order to use the CubeMX generated files. Without this option there was no PLL1 node in the device tree, and U-boot was unhappy.

**Comment by kmaincent** [comment]
Hello, thanks for your work.
There are few points to be fixed to accept your merge request:
- We need also a base defconfig for the STM32MP157F-DK2 as done for the other board.
- Add some documentation about it.
- Maybe use a common overlay for the sound config and 3 specific ones for the extlinux.

FYI, I am currently working on the v2022.02 version which will have this, and I will probably use what you have already done.

**Comment by tpetazzoni** [comment]
This has been addressed in the recently published st/2022.02 branch, together with lots of other improvements.

**Pull request closed without merging**
